### ISSUE TITLE
Fix home page resizing ui issues

### ISSUE THREAD

**Issue by wu-jacob** [BOLT-UBC/BOLT-website#3]
Acceptance criteria:
- home page text is legible when screen is resized
- absolute positioning is changed where needed (there might be a lot so don't worry about changing them all for now)
- try to make a single media query css (not 4 as we currently have)
![image](https://github.com/user-attachments/assets/2bb474c4-3473-437b-9a35-0444acca09d1)
![image](https://github.com/user-attachments/assets/b941a32d-8ffd-40d0-8c93-0483e1019ca2)

**Comment by sonatuna** [comment]
will fix spacing and push
