### ISSUE TITLE
Design database schema for bolt user sign up system

### ISSUE THREAD

**Issue by wu-jacob** [BOLT-UBC/BOLT-website#6]
- Decide on SQL vs noSQL
- Make schema (what data we want to store)
- Probably email, consider authentication (potentially store keys), names, student id, year

**Comment by angelafeliciaa** [comment]
SQL + Auth0?
![Image](https://github.com/user-attachments/assets/a23866f5-e8b2-4d5f-bdb0-80602870a46a)

**Comment by angelafeliciaa** [comment]
small int for year_of_study
